In [ ]:
!apt-get update
!apt-get install -y openjdk-11-jdk

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [83.8 kB]
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:7 https://cli.github.com/packages stable/main amd64 Packages [356 B]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,674 kB]
Get:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,887 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,640 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:16 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,288 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,293 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,571 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,999 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,605 kB]
Fetched 412 kB in 8s (51.2 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core fonts-dejavu-core fonts-dejavu-extra gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxt-dev libxtst6 libxxf86dga1
  openjdk-11-jdk-headless openjdk-11-jre openjdk-11-jre-headless
  session-migration x11-utils
Suggested packages:
  libxt-doc openjdk-11-demo openjdk-11-source visualvm libnss-mdns
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic mesa-utils
The following NEW packages will be installed:
  at-spi2-core fonts-dejavu-core fonts-dejavu-extra gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxt-dev libxtst6 libxxf86dga1
  openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre
  openjdk-11-jre-headless session-migration x11-utils
0 upgraded, 20 newly installed, 0 to remove and 35 not upgraded.
Need to get 124 MB of archives.
After this operation, 277 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxt-dev amd64 1:1.2.1-1 [396 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre-headless amd64 11.0.29+7-1ubuntu1~22.04 [42.6 MB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre amd64 11.0.29+7-1ubuntu1~22.04 [214 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.29+7-1ubuntu1~22.04 [73.6 MB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk amd64 11.0.29+7-1ubuntu1~22.04 [2,984 kB]
Fetched 124 MB in 6s (21.5 MB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../05-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../06-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../11-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../12-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../13-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../14-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../15-libxt-dev_1%3a1.2.1-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../16-openjdk-11-jre-headless_11.0.29+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.29+7-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../17-openjdk-11-jre_11.0.29+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.29+7-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jdk-headless:amd64.
Preparing to unpack .../18-openjdk-11-jdk-headless_11.0.29+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jdk-headless:amd64 (11.0.29+7-1ubuntu1~22.04) ...
Selecting previously unselected package openjdk-11-jdk:amd64.
Preparing to unpack .../19-openjdk-11-jdk_11.0.29+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jdk:amd64 (11.0.29+7-1ubuntu1~22.04) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up openjdk-11-jre-headless:amd64 (11.0.29+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up openjdk-11-jre:amd64 (11.0.29+7-1ubuntu1~22.04) ...
Setting up openjdk-11-jdk-headless:amd64 (11.0.29+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libxt-dev:amd64 (1:1.2.1-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up openjdk-11-jdk:amd64 (11.0.29+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.7) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...

In [ ]:
!java -version

openjdk version "17.0.17" 2025-10-21
OpenJDK Runtime Environment (build 17.0.17+10-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.17+10-Ubuntu-122.04, mixed mode, sharing)

In [ ]:
!git clone https://github.com/synthetichealth/synthea.git

Cloning into 'synthea'...
remote: Enumerating objects: 72369, done.
remote: Counting objects: 100% (745/745), done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 72369 (delta 599), reused 458 (delta 458), pack-reused 71624 (from 2)
Receiving objects: 100% (72369/72369), 799.76 MiB | 29.13 MiB/s, done.
Resolving deltas: 100% (42885/42885), done.

In [ ]:
%cd synthea

/content/synthea

In [ ]:
!ls output

ls: cannot access 'output': No such file or directory

In [ ]:
!pwd

/content/synthea

In [ ]:
!bash run_synthea -p 2000 --exporter.csv.export=true

Streaming output truncated to the last 5000 lines.
Loading Lookup Table: beta_blocker_carvedilol_product_distribution.csv
Loading Lookup Table: beta_blocker_labetalol_product_distribution.csv
Loading Lookup Table: beta_blocker_metoprolol_product_distribution.csv
Loading Lookup Table: beta_blocker_nebivolol_product_distribution.csv
Loading Lookup Table: beta_blocker_propranolol_product_distribution.csv



<==========---> 80% EXECUTING [2m 6s]> :run> IDLELoading submodule modules/medications/ear_infection_antibiotic.json
Loading submodule modules/medications/emergency_inhaler.json
Loading Lookup Table: emergency_inhaler_ingredient_distribution.csv
Loading Lookup Table: emergency_inhaler_albuterol_product_distribution.csv
Loading Lookup Table: emergency_inhaler_levalbuterol_product_distribution.csv



<==========---> 80% EXECUTING [2m 6s]> :run> IDLELoading submodule modules/medications/hypertension_medication.json
Loading submodule modules/medications/maintenance_inhaler.json


<==========---> 80% EXECUTING [2m 6s]> :run> IDLELoading Lookup Table: maintenance_inhaler_ingredient_distribution.csv
Loading Lookup Table: maintenance_inhaler_beclomethasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_budesonide_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_fluticasone_product_distribution.csv
Loading Lookup Table: maintenance_inhaler_mometasone_product_distribution.csv
Loading submodule modules/medications/moderate_opioid_pain_reliever.json
Loading submodule modules/medications/otc_antihistamine.json
Loading submodule modules/medications/otc_pain_reliever.json



<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/medications/statin.json
Loading Lookup Table: statin_ingredient_distribution.csv
Loading Lookup Table: statin_atorvastatin_product_distribution.csv
Loading Lookup Table: statin_ezetimibe_simvastatin_product_distribution.csv
Loading Lookup Table: statin_lovastatin_product_distribution.csv
Loading Lookup Table: statin_pitavastatin_product_distribution.csv
Loading Lookup Table: statin_pravastatin_product_distribution.csv



<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading Lookup Table: statin_rosuvastatin_product_distribution.csv
Loading Lookup Table: statin_simvastatin_product_distribution.csv


<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/medications/strong_opioid_pain_reliever.json
Loading submodule modules/metabolic_syndrome/amputations.json


<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/metabolic_syndrome/diabetic_retinopathy_diagnoses.json
Loading submodule modules/metabolic_syndrome/diabetic_retinopathy_progression.json


<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/metabolic_syndrome/dme_supplies.json
Loading submodule modules/metabolic_syndrome/kidney_conditions.json


<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/metabolic_syndrome/medications.json

<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/snf/skilled_nursing_facility.json

<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/surgery/general_anesthesia.json

<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/total_joint_replacement/functional_status_assessments.json
Loading submodule modules/uti/abx_tx.json


<==========---> 80% EXECUTING [2m 7s]> :run> IDLELoading submodule modules/uti/ambulatory_eval.json
Loading submodule modules/uti/ambulatory_path.json


<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading submodule modules/uti/ed_bundle.json

<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading submodule modules/uti/ed_eval.json

<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading submodule modules/uti/ed_path.json
Loading submodule modules/uti/gu_pregnancy_check.json
Loading submodule modules/uti/hpi.json



<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading submodule modules/uti/lab_follow_up.json
Loading submodule modules/uti/labs.json
Loading submodule modules/uti/telemed_path.json



<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading submodule modules/veterans/veteran_suicide_probabilities.json

<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading submodule modules/weight_loss/mend_week.json
Loading module modules/acute_myeloid_leukemia.json


<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading Lookup Table: AML.csv

<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading module modules/allergic_rhinitis.json
Loading module modules/allergies.json


<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading module modules/anemia___unknown_etiology.json
Loading module modules/appendicitis.json


<==========---> 80% EXECUTING [2m 8s]> :run> IDLELoading module modules/asthma.json
Loading module modules/atopy.json
Loading module modules/atrial_fibrillation.json



<==========---> 80% EXECUTING [2m 9s]> :run> IDLELoading module modules/attention_deficit_disorder.json

<==========---> 80% EXECUTING [2m 9s]> :run> IDLELoading module modules/bone_marrow_transplant.json

<==========---> 80% EXECUTING [2m 9s]> :run> IDLELoading module modules/breast_cancer.json

<==========---> 80% EXECUTING [2m 9s]> :run> IDLELoading module modules/bronchitis.json

<==========---> 80% EXECUTING [2m 9s]> :run> IDLELoading module modules/cerebral_palsy.json

<==========---> 80% EXECUTING [2m 9s]> :run> IDLELoading module modules/chronic_kidney_disease.json

<==========---> 80% EXECUTING [2m 10s]> :run> IDLELoading module modules/colorectal_cancer.json

<==========---> 80% EXECUTING [2m 10s]> :run> IDLELoading module modules/congestive_heart_failure.json

<==========---> 80% EXECUTING [2m 10s]> :run> IDLELoading module modules/contraceptive_maintenance.json
Loading module modules/contraceptives.json


<==========---> 80% EXECUTING [2m 10s]> :run> IDLELoading module modules/copd.json

<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading module modules/covid19.json

<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading Lookup Table: covid19_prob.csv
Loading module modules/cystic_fibrosis.json


<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading module modules/dementia.json

<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading module modules/dental_and_oral_examination.json

<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading module modules/dentures.json

<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading module modules/dermatitis.json

<==========---> 80% EXECUTING [2m 11s]> :run> IDLELoading module modules/diabetic_retinopathy_treatment.json
Loading Lookup Table: diabetic_retinopathy_followup.csv
Loading module modules/dialysis.json



<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading module modules/ear_infections.json
Loading module modules/epilepsy.json


<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading module modules/female_reproduction.json
Loading module modules/fibromyalgia.json
Loading module modules/food_allergies.json
Loading module modules/gallstones.json



<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading module modules/gout.json
Loading module modules/hiv_care.json


<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading Lookup Table: hiv_care.csv
Loading module modules/hiv_diagnosis.json
Loading Lookup Table: hiv_mortality_later.csv
Loading Lookup Table: hiv_mortality_early.csv



<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading Lookup Table: hiv_mortality_very_early.csv
Loading Lookup Table: hiv_diagnosis_early.csv
Loading Lookup Table: hiv_diagnosis_later.csv
Loading module modules/home_health_treatment.json



<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading module modules/home_hospice_snf.json
Loading module modules/homelessness.json


<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading module modules/hospice_treatment.json
Loading module modules/hypertension.json


<==========---> 80% EXECUTING [2m 12s]> :run> IDLELoading module modules/hypothyroidism.json
Loading module modules/injuries.json


<==========---> 80% EXECUTING [2m 12s]> :run> IDLE<==========---> 80% EXECUTING [2m 13s]Loading module modules/kidney_transplant.json

<==========---> 80% EXECUTING [2m 13s]> :run> IDLELoading module modules/lung_cancer.json

<==========---> 80% EXECUTING [2m 13s]> :run> IDLELoading module modules/lupus.json
Loading module modules/mTBI.json
Loading module modules/med_rec.json
Loading module modules/mend_program.json



<==========---> 80% EXECUTING [2m 13s]> :run> IDLELoading module modules/metabolic_syndrome_care.json
Loading module modules/metabolic_syndrome_disease.json
Loading module modules/myocardial_infarction.json



<==========---> 80% EXECUTING [2m 13s]> :run> IDLELoading module modules/opioid_addiction.json

<==========---> 80% EXECUTING [2m 13s]> :run> IDLELoading module modules/osteoarthritis.json
Loading module modules/osteoporosis.json
Loading module modules/pregnancy.json



<==========---> 80% EXECUTING [2m 13s]> :run> IDLELoading module modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json

<==========---> 80% EXECUTING [2m 13s]> :run> IDLE<==========---> 80% EXECUTING [2m 14s]Loading module modules/rheumatoid_arthritis.json

<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/self_harm.json

<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/sepsis.json

<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/sexual_activity.json
Loading module modules/sinusitis.json


<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/sleep_apnea.json

<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/sore_throat.json

<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/spina_bifida.json

<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/stable_ischemic_heart_disease.json
Loading module modules/stroke.json


<==========---> 80% EXECUTING [2m 14s]> :run> IDLELoading module modules/total_joint_replacement.json
Loading module modules/trigger_bone_marrow_transplant.json


<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/urinary_tract_infections.json
Loading Lookup Table: uti.csv
Loading Lookup Table: uti_recurrence.csv
Loading module modules/veteran.json



<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/veteran_hyperlipidemia.json
Loading module modules/veteran_lung_cancer.json


<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/veteran_mdd.json

<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/veteran_prostate_cancer.json

<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/veteran_ptsd.json

<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/veteran_self_harm.json

<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/veteran_substance_abuse_conditions.json
Loading module modules/veteran_substance_abuse_treatment.json


<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/vhd_aortic.json
Loading Lookup Table: vhd_as.csv
Loading Lookup Table: vhd_ar.csv
Loading module modules/vhd_mitral.json
Loading Lookup Table: vhd_mr.csv
Loading Lookup Table: vhd_ms.csv



<==========---> 80% EXECUTING [2m 15s]> :run> IDLELoading module modules/vhd_pulmonic.json
Loading Lookup Table: vhd_ps.csv
Loading Lookup Table: vhd_pr.csv
Loading module modules/vhd_tricuspid.json
Loading Lookup Table: vhd_tr.csv



<==========---> 80% EXECUTING [2m 16s]> :run> IDLELoading Lookup Table: vhd_ts.csv
Loading module modules/wellness_encounters.json


<==========---> 80% EXECUTING [2m 16s]> :run> IDLERunning with options:
Population: 2000
Seed: 1769885575547
Provider Seed:1769885575547
Reference Time: 1769885575547
Location: Massachusetts
Min Age: 0
Max Age: 140



<==========---> 80% EXECUTING [2m 16s]> :run> IDLE<==========---> 80% EXECUTING [2m 17s]<==========---> 80% EXECUTING [2m 18s]1 -- Phyliss206 Osinski784 (24 y/o F) Blackstone, Massachusetts  (32998)

<==========---> 80% EXECUTING [2m 18s]> :run> IDLE<==========---> 80% EXECUTING [2m 19s]2 -- Mitch821 Hettinger594 (59 y/o M) South Deerfield, Massachusetts  (80129)

<==========---> 80% EXECUTING [2m 19s]> :run> IDLE<==========---> 80% EXECUTING [2m 20s]<==========---> 80% EXECUTING [2m 21s]<==========---> 80% EXECUTING [2m 22s]<==========---> 80% EXECUTING [2m 23s]<==========---> 80% EXECUTING [2m 24s]<==========---> 80% EXECUTING [2m 25s]4 -- Marlana402 Purdy2 (23 y/o F) Boston, Massachusetts  (33111)

<==========---> 80% EXECUTING [2m 25s]> :run> IDLE<==========---> 80% EXECUTING [2m 26s]3 -- Flo729 Tracie996 Treutel973 (43 y/o F) Boston, Massachusetts  (60064)

<==========---> 80% EXECUTING [2m 26s]> :run> IDLE<==========---> 80% EXECUTING [2m 27s]<==========---> 80% EXECUTING [2m 28s]<==========---> 80% EXECUTING [2m 29s]<==========---> 80% EXECUTING [2m 30s]6 -- Darron84 Kuhlman484 (66 y/o M) Springfield, Massachusetts  (91485)

<==========---> 80% EXECUTING [2m 30s]> :run> IDLE5 -- Graciela518 Beth967 Padberg411 (63 y/o F) Tewksbury, Massachusetts  (107721)

<==========---> 80% EXECUTING [2m 30s]> :run> IDLE<==========---> 80% EXECUTING [2m 31s]<==========---> 80% EXECUTING [2m 32s]7 -- María José279 Maricarmen445 Martínez540 (49 y/o F) Taunton, Massachusetts DECEASED (69794)

<==========---> 80% EXECUTING [2m 32s]> :run> IDLE<==========---> 80% EXECUTING [2m 33s]<==========---> 80% EXECUTING [2m 34s]<==========---> 80% EXECUTING [2m 35s]<==========---> 80% EXECUTING [2m 36s]7 -- Berta524 Ana972 Garay400 (44 y/o F) Taunton, Massachusetts DECEASED (61404)

<==========---> 80% EXECUTING [2m 36s]> :run> IDLE<==========---> 80% EXECUTING [2m 37s]7 -- Adriana394 Ávila241 (53 y/o F) Taunton, Massachusetts  (73578)

<==========---> 80% EXECUTING [2m 38s]> :run> IDLE8 -- Lauren941 Ullrich385 (67 y/o M) Billerica, Massachusetts  (100545)

<==========---> 80% EXECUTING [2m 38s]> :run> IDLE<==========---> 80% EXECUTING [2m 39s]9 -- Mickie472 Jacqualine965 Gulgowski816 (52 y/o F) Lawrence, Massachusetts  (71515)

<==========---> 80% EXECUTING [2m 39s]> :run> IDLE<==========---> 80% EXECUTING [2m 40s]<==========---> 80% EXECUTING [2m 41s]10 -- Rubén780 Mireles421 (43 y/o M) Springfield, Massachusetts  (59040)

<==========---> 80% EXECUTING [2m 41s]> :run> IDLE<==========---> 80% EXECUTING [2m 42s]12 -- Hoyt490 Orn563 (0 y/o M) Salem, Massachusetts  (1301)

<==========---> 80% EXECUTING [2m 42s]> :run> IDLE<==========---> 80% EXECUTING [2m 43s]11 -- Ilse197 Mikki421 Champlin946 (66 y/o F) East Douglas, Massachusetts  (92386)

<==========---> 80% EXECUTING [2m 43s]> :run> IDLE13 -- Kaley842 O'Keefe54 (28 y/o F) Boston, Massachusetts DECEASED (39408)

<==========---> 80% EXECUTING [2m 43s]> :run> IDLE<==========---> 80% EXECUTING [2m 44s]<==========---> 80% EXECUTING [2m 45s]14 -- Wilfredo622 Berge125 (55 y/o M) Chicopee, Massachusetts  (74195)

<==========---> 80% EXECUTING [2m 45s]> :run> IDLE13 -- Takisha161 Larhonda769 Kilback373 (50 y/o F) Boston, Massachusetts  (75609)

<==========---> 80% EXECUTING [2m 45s]> :run> IDLE<==========---> 80% EXECUTING [2m 46s]Waiting for threads to finish... java.util.concurrent.ThreadPoolExecutor@25a94b55[Shutting down, pool size = 2, active threads = 2, queued tasks = 1984, completed tasks = 14]

<==========---> 80% EXECUTING [2m 46s]> :run> IDLE15 -- Ozella681 Roob72 (59 y/o F) Ashby, Massachusetts  (81331)

<==========---> 80% EXECUTING [2m 46s]> :run> IDLE16 -- Sena221 Roseann182 Williamson769 (45 y/o F) Westfield, Massachusetts  (75397)

<==========---> 80% EXECUTING [2m 47s]> :run> IDLE17 -- Cindi877 Volkman526 (13 y/o F) Worcester, Massachusetts  (18984)

<==========---> 80% EXECUTING [2m 47s]> :run> IDLE<==========---> 80% EXECUTING [2m 48s]<==========---> 80% EXECUTING [2m 49s]18 -- Margarite168 Towne435 (12 y/o F) Athol, Massachusetts  (16197)

<==========---> 80% EXECUTING [2m 49s]> :run> IDLE<==========---> 80% EXECUTING [2m 50s]19 -- Kevin729 Boyle917 (19 y/o M) Lawrence, Massachusetts  (25962)

<==========---> 80% EXECUTING [2m 50s]> :run> IDLE20 -- Cordie578 Jakubowski832 (24 y/o F) Lowell, Massachusetts  (33279)

<==========---> 80% EXECUTING [2m 50s]> :run> IDLE21 -- Eulalia351 Crooks415 (1 y/o F) Hudson, Massachusetts  (2305)

<==========---> 80% EXECUTING [2m 50s]> :run> IDLE<==========---> 80% EXECUTING [2m 51s]22 -- Percy315 Jaskolski867 (29 y/o M) Hopedale, Massachusetts  (39957)

<==========---> 80% EXECUTING [2m 51s]> :run> IDLE<==========---> 80% EXECUTING [2m 52s]23 -- Damon455 Ziemann98 (44 y/o M) Weston, Massachusetts  (64146)

<==========---> 80% EXECUTING [2m 52s]> :run> IDLE24 -- Gale827 Borer986 (32 y/o M) Scituate, Massachusetts DECEASED (44040)

<==========---> 80% EXECUTING [2m 52s]> :run> IDLE<==========---> 80% EXECUTING [2m 53s]24 -- Adrian111 Mueller846 (47 y/o M) Scituate, Massachusetts  (63098)

<==========---> 80% EXECUTING [2m 54s]> :run> IDLE25 -- Yan646 Deckow585 (50 y/o F) Franklin, Massachusetts DECEASED (72327)

<==========---> 80% EXECUTING [2m 54s]> :run> IDLE26 -- Annis955 Larkin917 (15 y/o F) Northampton, Massachusetts  (19827)

<==========---> 80% EXECUTING [2m 54s]> :run> IDLE<==========---> 80% EXECUTING [2m 55s]<==========---> 80% EXECUTING [2m 56s]<==========---> 80% EXECUTING [2m 57s]25 -- Keisha459 Elina789 Ruecker817 (59 y/o F) Franklin, Massachusetts  (80892)

<==========---> 80% EXECUTING [2m 57s]> :run> IDLE27 -- Quintin944 Rohan584 (84 y/o M) Stow, Massachusetts DECEASED (116154)

<==========---> 80% EXECUTING [2m 57s]> :run> IDLE<==========---> 80% EXECUTING [2m 58s]28 -- Arron144 Dach178 (49 y/o M) Waltham, Massachusetts  (68960)

<==========---> 80% EXECUTING [2m 58s]> :run> IDLE<==========---> 80% EXECUTING [2m 59s]29 -- Hilario934 Lindgren255 (25 y/o M) Lowell, Massachusetts  (33674)

<==========---> 80% EXECUTING [2m 59s]> :run> IDLE30 -- Tom274 Reinger292 (21 y/o M) Gardner, Massachusetts  (28864)

<==========---> 80% EXECUTING [2m 59s]> :run> IDLE<==========---> 80% EXECUTING [3m]<==========---> 80% EXECUTING [3m 1s]31 -- Calandra120 Marian936 Greenfelder433 (61 y/o F) Templeton, Massachusetts  (85737)

<==========---> 80% EXECUTING [3m 1s]> :run> IDLE<==========---> 80% EXECUTING [3m 2s]27 -- Joel444 Adams676 (101 y/o M) Stow, Massachusetts  (221285)

<==========---> 80% EXECUTING [3m 2s]> :run> IDLE32 -- Ervin886 Baumbach677 (31 y/o M) Newton, Massachusetts  (42568)

<==========---> 80% EXECUTING [3m 2s]> :run> IDLE<==========---> 80% EXECUTING [3m 3s]33 -- Abram53 Larson43 (12 y/o M) West Springfield, Massachusetts  (17211)

<==========---> 80% EXECUTING [3m 3s]> :run> IDLE<==========---> 80% EXECUTING [3m 4s]<==========---> 80% EXECUTING [3m 5s]34 -- Courtney281 Bahringer146 (60 y/o M) Needham, Massachusetts  (83720)

<==========---> 80% EXECUTING [3m 5s]> :run> IDLE<==========---> 80% EXECUTING [3m 6s]35 -- Nikita578 Crooks415 (3 y/o F) Boston, Massachusetts  (4637)

<==========---> 80% EXECUTING [3m 6s]> :run> IDLE<==========---> 80% EXECUTING [3m 7s]36 -- Anton902 Baumbach677 (23 y/o M) Marlborough, Massachusetts  (31797)

<==========---> 80% EXECUTING [3m 8s]> :run> IDLE37 -- Octavio643 Fonseca493 (6 y/o M) Haverhill, Massachusetts  (9325)

<==========---> 80% EXECUTING [3m 8s]> :run> IDLE<==========---> 80% EXECUTING [3m 9s]<==========---> 80% EXECUTING [3m 10s]38 -- Victor265 McLaughlin530 (46 y/o M) Revere, Massachusetts  (64400)

<==========---> 80% EXECUTING [3m 10s]> :run> IDLE<==========---> 80% EXECUTING [3m 11s]<==========---> 80% EXECUTING [3m 12s]39 -- Mirtha993 Coletta724 Glover433 (69 y/o F) Boston, Massachusetts  (97492)

<==========---> 80% EXECUTING [3m 12s]> :run> IDLE<==========---> 80% EXECUTING [3m 13s]40 -- Salvador46 Wehner319 (59 y/o M) Woburn, Massachusetts  (83358)


In [ ]:
!ls output

csv  fhir  metadata

In [ ]:
!ls output/csv

allergies.csv		 encounters.csv       patients.csv
careplans.csv		 imaging_studies.csv  payers.csv
claims.csv		 immunizations.csv    payer_transitions.csv
claims_transactions.csv  medications.csv      procedures.csv
conditions.csv		 observations.csv     providers.csv
devices.csv		 organizations.csv    supplies.csv

In [ ]:
import pandas as pd

patients = pd.read_csv("output/csv/patients.csv")
observations = pd.read_csv("output/csv/observations.csv")
claims = pd.read_csv("output/csv/claims.csv")

In [ ]:
patients.shape

(2302, 28)

In [ ]:
observations.shape

(1711338, 9)

In [ ]:
claims.shape

(243539, 31)

In [ ]:
patients["BIRTHDATE"].value_counts().head()

BIRTHDATE
1918-01-11    11
1918-11-27     8
1938-04-29     7
1918-10-23     6
1926-10-12     6
Name: count, dtype: int64

In [ ]:
observations[observations["DESCRIPTION"].str.contains("Blood pressure", na=False)]["VALUE"].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: VALUE, dtype: object

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

ValueError: mount failed

In [ ]:
!cp -r /content/synthea/output /content/drive/MyDrive/synthea_output